### PR TITLE
fix the handling of the API key in user_data.sh

### PR DESCRIPTION
**Pull request by gmewhinney**
I had inadvertently embedded an API key in the DNS part of user_data.sh, so I fixed that.
Also I removed 3 scripts from a staging directory that did not need to be there.

### CODE REVIEW

**Comment by adamsla** [comment]
You better invalidate that key and get a new one.  People troll github for API keys all the time, and the fact that you pushed it, makes it pretty much public, even though you removed it.

**Comment by adamsla** [comment]
Also, please signoff.

**Comment by gmewhinney** [comment]
I deleted the API key soon after the code went live so I think we are OK there.  I do not have much experience with pull requests, can you help me understand what I need to do to "signoff"?  Thanks.

**Comment by adamsla** [comment]
@gmewhinney read the DCO note in this repository for the instructions and your responsibilities.  Basically, you have to simply add the comment:

```
signed-off: myrealemail@address.com
```

To this pull request.

**Comment by gmewhinney** [comment]
OK, I amended the commit message and added a  signoff.  Thanks.

**Comment by adamsla** [comment]
I don't see it.  Should be a comment on this pull request which I still don't see.  Just add the comment here with your real email address please.

**Comment by gmewhinney** [comment]
signed-off-by: Greg Mewhinney <mewhinne@us.ibm.com>

I think it is actually there in the commit message now, but for some reason it is hidden until you click on the 3 dots to the right.  Here's a screenshot:

image

**Comment by adamsla** [comment]
@SMark-Black, Mark your call on the merge.

**Pull request merged**
